Blumea/Blumea

- bloomFilterCounting/main.js
CountingBloomFilter implementation version 1.
> :package: CountingBloomFilter v1 init

- README.md
> :sparkles: documentation enhancements

- README.md
> :sparkles: documentation enhancements #7

- classicalBloom/main.js
- logger/logger.js
- Logger module changes.
- ClassicalBloom module log changes.
> ✏️ logger improvements

- partitionedBloom/main.js
Updated code for bloom filter: Partitioned
Added various functions (inside partitioned bloom filter) for other purposes.
need to check with tests once .
> updated code for partitioned bloom filter

- countingBloom/main.js
> :wrench: input bug fix for Counting Bloom

- README.md
- classicalBloom/main.js
Can't merge.
Need to add sample code.
> :wrench:  updated read-me for paritioned bloom filter

- classicalBloom/main.js
- index.js
- logger/config.js
- logger/logger.js
- package.json
- scalableBloom/main.js
> :jigsaw: init Blumea Logger module

- classicalBloom/main.js
> :building_construction: classical bloom code refactor

- countingBloom/main.js
>  :building_construction: counting bloom code refactor

- partitionedBloom/main.js
Issue references: 
Logger update #39 
Bug fix for serverless app - Missing input type checks for `item_count` and `false_positive`
> :bug: partitioned bloom bug fix + refactor

- partitionedBloom/main.js
@akashchouhan16 Please pull and try to run. Let's see if it still causes trouble.
> Added check for partition-count

- index.js
- package.json
- scalableBloom/main-v2.js
- scalableBloom/main.js
> :jigsaw: init Scalable Bloom Filter module for 1.0.8

- cuckooBloom/main.js
@akashchouhan16 Have a look, and let me know if it causes the issue.
> implemented cuckoo bloom filter

- README.md
- cuckooBloom/main.js
- index.js
@akashchouhan16 i think i made a pull with previous pr lol
> :package:added readme for cuckoo filter/fixed index-js

- .github/workflows/npm-publish.yml
Triggered on push to branch `publish`
> :wrench: CI config - NPM publish

- README.md
- package.json
- Updated Authors
- Updated Readme
> :octocat: Documentation & Package Updates v1.1.0

- README.md
- cuckooBloom/main.js
@akashchouhan16 Updated logs. Please test once.
> :hammer:updated logs in cuckoo

- README.md
- build/countingBloom/main.js
> ✏️ Update to Counting Bloom Doc

- build/classicalBloom/main.js
- build/countingBloom/main.js
- build/cuckooBloom/main.js
- build/partitionedBloom/main.js
- build/scalableBloom/main.js
- index.js
- logger/logger.js
- package.json
Includes:
- Logger module code refactor. Removed redundancy with the code.
- Cuckoo Bloom major bug fix. #71
> 🔖 CI Trigger: Publish patch release v1.1.1 

- .github/workflows/codeql.yml
Removed daily scheduled CodeQL pipeline.
> :wrench: CI config - codeql cron update

- .npmignore
- test/classical.test.js
- test/counting.test.js
- test/cuckoo.test.js
- test/partitioned.test.js
- test/scalable.test.js
- Unit tests previously took longer time to run because of the multiple object creation.
- Init Scalable Bloom unit test.
> 🧪  updated unit tests
